config/routes.rb
Rails.application.routes.draw do
  root to: "towns#index"

  #resources :users
  resources :towns
  resources :sections
  resources :kal_cities
  resources :regional_unities
  resources :kap_cities
  resources :prefectures
  resources :regions

  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kal_city.rb
class KalCity < ApplicationRecord
  belongs_to :regional_unity
  has_many :sections
end

app/controllers/kal_cities_controller.rb
class KalCitiesController < ApplicationController
  before_action :set_kal_city, only: [:show, :edit, :update, :destroy]

  # GET /kal_cities
  # GET /kal_cities.json
  def index
    @kal_cities = KalCity.paginate(page: params[:page], per_page:10)
  end

  # GET /kal_cities/1
  # GET /kal_cities/1.json
  def show
  end

  # GET /kal_cities/new
  def new
    @kal_city = KalCity.new
  end

  # GET /kal_cities/1/edit
  def edit
  end

  # POST /kal_cities
  # POST /kal_cities.json
  def create
    @kal_city = KalCity.new(kal_city_params)

    respond_to do |format|
      if @kal_city.save
        format.html { redirect_to @kal_city, notice: 'Kal city was successfully created.' }
        format.json { render :show, status: :created, location: @kal_city }
      else
        format.html { render :new }
        format.json { render json: @kal_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kal_cities/1
  # PATCH/PUT /kal_cities/1.json
  def update
    respond_to do |format|
      if @kal_city.update(kal_city_params)
        format.html { redirect_to @kal_city, notice: 'Kal city was successfully updated.' }
        format.json { render :show, status: :ok, location: @kal_city }
      else
        format.html { render :edit }
        format.json { render json: @kal_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kal_cities/1
  # DELETE /kal_cities/1.json
  def destroy
    @kal_city.destroy
    respond_to do |format|
      format.html { redirect_to kal_cities_url, notice: 'Kal city was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kal_city
      @kal_city = KalCity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kal_city_params
      params.require(:kal_city).permit(:name, :type, :regional_unity_id)
    end
end

app/helpers/kal_cities_helper.rb
module KalCitiesHelper
end

app/views/kal_cities/_form.html.erb
<%= form_for(kal_city) do |f| %>
  <% if kal_city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kal_city.errors.count, "error") %> prohibited this kal_city from being saved:</h2>

      <ul>
      <% kal_city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :regional_unity_id %>
    <%= f.text_field :regional_unity_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kal_cities/edit.html.erb
<h1>Editing Kal City</h1>

<%= render 'form', kal_city: @kal_city %>

<%= link_to 'Show', @kal_city %> |
<%= link_to 'Back', kal_cities_path %>

app/views/kal_cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kal Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Regional unity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kal_cities.each do |kal_city| %>
      <tr>
        <td><%= kal_city.name %></td>
        <td><%= kal_city.title %></td>
        <td><%= kal_city.regional_unity %></td>
        <td><%= link_to 'Show', kal_city %></td>
        <td><%= link_to 'Edit', edit_kal_city_path(kal_city) %></td>
        <td><%= link_to 'Destroy', kal_city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @kal_cities %>
<br>

<%= link_to 'New Kal City', new_kal_city_path %>

app/views/kal_cities/new.html.erb
<h1>New Kal City</h1>

<%= render 'form', kal_city: @kal_city %>

<%= link_to 'Back', kal_cities_path %>

app/views/kal_cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kal_city.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @kal_city.title %>
</p>

<p>
  <strong>Regional unity:</strong>
  <%= @kal_city.regional_unity %>
</p>

<%= link_to 'Edit', edit_kal_city_path(@kal_city) %> |
<%= link_to 'Back', kal_cities_path %>