config/routes.rb
Rails.application.routes.draw do
  root to: "towns#index"

  #resources :users
  resources :towns
  resources :sections
  resources :kal_cities
  resources :regional_unities
  resources :kap_cities
  resources :prefectures
  resources :regions

  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/regional_unity.rb
class RegionalUnity < ApplicationRecord
  belongs_to :region
  has_many :kal_cities
end

app/controllers/regional_unities_controller.rb
class RegionalUnitiesController < ApplicationController
  before_action :set_regional_unity, only: [:show, :edit, :update, :destroy]

  # GET /regional_unities
  # GET /regional_unities.json
  def index
    @regional_unities = RegionalUnity.paginate(page: params[:page], per_page:10)
  end

  # GET /regional_unities/1
  # GET /regional_unities/1.json
  def show
  end

  # GET /regional_unities/new
  def new
    @regional_unity = RegionalUnity.new
  end

  # GET /regional_unities/1/edit
  def edit
  end

  # POST /regional_unities
  # POST /regional_unities.json
  def create
    @regional_unity = RegionalUnity.new(regional_unity_params)

    respond_to do |format|
      if @regional_unity.save
        format.html { redirect_to @regional_unity, notice: 'Regional unity was successfully created.' }
        format.json { render :show, status: :created, location: @regional_unity }
      else
        format.html { render :new }
        format.json { render json: @regional_unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /regional_unities/1
  # PATCH/PUT /regional_unities/1.json
  def update
    respond_to do |format|
      if @regional_unity.update(regional_unity_params)
        format.html { redirect_to @regional_unity, notice: 'Regional unity was successfully updated.' }
        format.json { render :show, status: :ok, location: @regional_unity }
      else
        format.html { render :edit }
        format.json { render json: @regional_unity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /regional_unities/1
  # DELETE /regional_unities/1.json
  def destroy
    @regional_unity.destroy
    respond_to do |format|
      format.html { redirect_to regional_unities_url, notice: 'Regional unity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_regional_unity
      @regional_unity = RegionalUnity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def regional_unity_params
      params.require(:regional_unity).permit(:name, :region_id)
    end
end

app/helpers/regional_unities_helper.rb
module RegionalUnitiesHelper
end

app/views/regional_unities/_form.html.erb
<%= form_for(regional_unity) do |f| %>
  <% if regional_unity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(regional_unity.errors.count, "error") %> prohibited this regional_unity from being saved:</h2>

      <ul>
      <% regional_unity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :region_id %>
    <%= f.text_field :region_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/regional_unities/edit.html.erb
<h1>Editing Regional Unity</h1>

<%= render 'form', regional_unity: @regional_unity %>

<%= link_to 'Show', @regional_unity %> |
<%= link_to 'Back', regional_unities_path %>

app/views/regional_unities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Regional Unities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Region</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @regional_unities.each do |regional_unity| %>
      <tr>
        <td><%= regional_unity.name %></td>
        <td><%= regional_unity.region %></td>
        <td><%= link_to 'Show', regional_unity %></td>
        <td><%= link_to 'Edit', edit_regional_unity_path(regional_unity) %></td>
        <td><%= link_to 'Destroy', regional_unity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @regional_unities %>
<br>

<%= link_to 'New Regional Unity', new_regional_unity_path %>

app/views/regional_unities/new.html.erb
<h1>New Regional Unity</h1>

<%= render 'form', regional_unity: @regional_unity %>

<%= link_to 'Back', regional_unities_path %>

app/views/regional_unities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @regional_unity.name %>
</p>

<p>
  <strong>Region:</strong>
  <%= @regional_unity.region %>
</p>

<%= link_to 'Edit', edit_regional_unity_path(@regional_unity) %> |
<%= link_to 'Back', regional_unities_path %>