config/routes.rb
Rails.application.routes.draw do
  root to: "towns#index"

  #resources :users
  resources :towns
  resources :sections
  resources :kal_cities
  resources :regional_unities
  resources :kap_cities
  resources :prefectures
  resources :regions

  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kap_city.rb
class KapCity < ApplicationRecord
  belongs_to :prefecture
  has_many :towns
end

app/controllers/kap_cities_controller.rb
class KapCitiesController < ApplicationController
  before_action :set_kap_city, only: [:show, :edit, :update, :destroy]

  # GET /kap_cities
  # GET /kap_cities.json
  def index
    @kap_cities = KapCity.paginate(page: params[:page], per_page:10)
  end

  # GET /kap_cities/1
  # GET /kap_cities/1.json
  def show
  end

  # GET /kap_cities/new
  def new
    @kap_city = KapCity.new
  end

  # GET /kap_cities/1/edit
  def edit
  end

  # POST /kap_cities
  # POST /kap_cities.json
  def create
    @kap_city = KapCity.new(kap_city_params)

    respond_to do |format|
      if @kap_city.save
        format.html { redirect_to @kap_city, notice: 'Kap city was successfully created.' }
        format.json { render :show, status: :created, location: @kap_city }
      else
        format.html { render :new }
        format.json { render json: @kap_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kap_cities/1
  # PATCH/PUT /kap_cities/1.json
  def update
    respond_to do |format|
      if @kap_city.update(kap_city_params)
        format.html { redirect_to @kap_city, notice: 'Kap city was successfully updated.' }
        format.json { render :show, status: :ok, location: @kap_city }
      else
        format.html { render :edit }
        format.json { render json: @kap_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kap_cities/1
  # DELETE /kap_cities/1.json
  def destroy
    @kap_city.destroy
    respond_to do |format|
      format.html { redirect_to kap_cities_url, notice: 'Kap city was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kap_city
      @kap_city = KapCity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kap_city_params
      params.require(:kap_city).permit(:name, :type, :prefecture_id)
    end
end

app/helpers/kap_cities_helper.rb
module KapCitiesHelper
end

app/views/kap_cities/_form.html.erb
<%= form_for(kap_city) do |f| %>
  <% if kap_city.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kap_city.errors.count, "error") %> prohibited this kap_city from being saved:</h2>

      <ul>
      <% kap_city.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :prefecture_id %>
    <%= f.text_field :prefecture_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/kap_cities/edit.html.erb
<h1>Editing Kap City</h1>

<%= render 'form', kap_city: @kap_city %>

<%= link_to 'Show', @kap_city %> |
<%= link_to 'Back', kap_cities_path %>

app/views/kap_cities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kap Cities</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Prefecture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kap_cities.each do |kap_city| %>
      <tr>
        <td><%= kap_city.name %></td>
        <td><%= kap_city.title %></td>
        <td><%= kap_city.prefecture %></td>
        <td><%= link_to 'Show', kap_city %></td>
        <td><%= link_to 'Edit', edit_kap_city_path(kap_city) %></td>
        <td><%= link_to 'Destroy', kap_city, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @kap_cities %>
<br>

<%= link_to 'New Kap City', new_kap_city_path %>

app/views/kap_cities/new.html.erb
<h1>New Kap City</h1>

<%= render 'form', kap_city: @kap_city %>

<%= link_to 'Back', kap_cities_path %>

app/views/kap_cities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @kap_city.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @kap_city.title %>
</p>

<p>
  <strong>Prefecture:</strong>
  <%= @kap_city.prefecture %>
</p>

<%= link_to 'Edit', edit_kap_city_path(@kap_city) %> |
<%= link_to 'Back', kap_cities_path %>