config/routes.rb
Rails.application.routes.draw do
  root to: "towns#index"

  #resources :users
  resources :towns
  resources :sections
  resources :kal_cities
  resources :regional_unities
  resources :kap_cities
  resources :prefectures
  resources :regions

  resources :sessions, only: [:new, :create, :destroy]

  get "/login" => "sessions#new", as: "login"
  delete "/logout" => "sessions#destroy", as: "logout"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/town.rb
class Town < ApplicationRecord	
  belongs_to :section
  belongs_to :kap_city
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: [:show, :edit, :update, :destroy]

  # GET /towns
  # GET /towns.json
  def index
    @towns = Town.paginate(page: params[:page], per_page:10)
  end

  # GET /towns/1
  # GET /towns/1.json
  def show
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns
  # POST /towns.json
  def create
    @town = Town.new(town_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to @town, notice: 'Town was successfully created.' }
        format.json { render :show, status: :created, location: @town }
      else
        format.html { render :new }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towns/1
  # PATCH/PUT /towns/1.json
  def update
    respond_to do |format|
      if @town.update(town_params)
        format.html { redirect_to @town, notice: 'Town was successfully updated.' }
        format.json { render :show, status: :ok, location: @town }
      else
        format.html { render :edit }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1
  # DELETE /towns/1.json
  def destroy
    @town.destroy
    respond_to do |format|
      format.html { redirect_to towns_url, notice: 'Town was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def town_params
      params.require(:town).permit(:name, :type, :kal_townID, :kap_townID, :kal_type, :kal_base, :population, :kap_type, :section_id, :kap_city_id)
    end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/towns/_form.html.erb
<%= form_for(town) do |f| %>
  <% if town.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
      <% town.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :kal_townID %>
    <%= f.text_field :kal_townID %>
  </div>

  <div class="field">
    <%= f.label :kap_townID %>
    <%= f.text_field :kap_townID %>
  </div>

  <div class="field">
    <%= f.label :kal_type %>
    <%= f.text_field :kal_type %>
  </div>

  <div class="field">
    <%= f.label :kal_base %>
    <%= f.text_field :kal_base %>
  </div>

  <div class="field">
    <%= f.label :population %>
    <%= f.text_field :population %>
  </div>

  <div class="field">
    <%= f.label :kap_type %>
    <%= f.text_field :kap_type %>
  </div>

  <div class="field">
    <%= f.label :section_id %>
    <%= f.text_field :section_id %>
  </div>

  <div class="field">
    <%= f.label :kap_city_id %>
    <%= f.text_field :kap_city_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/towns/edit.html.erb
<h1>Editing Town</h1>

<%= render 'form', town: @town %>

<%= link_to 'Show', @town %> |
<%= link_to 'Back', towns_path %>

app/views/towns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Towns</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Kal townid</th>
      <th>Kap townid</th>
      <th>Kal type</th>
      <th>Kal base</th>
      <th>Population</th>
      <th>Kap type</th>
      <th>Section</th>
      <th>Kap city</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @towns.each do |town| %>
      <tr>
        <td><%= town.name %></td>
        <td><%= town.title %></td>
        <td><%= town.kal_townID %></td>
        <td><%= town.kap_townID %></td>
        <td><%= town.kal_type %></td>
        <td><%= town.kal_base %></td>
        <td><%= town.population %></td>
        <td><%= town.kap_type %></td>
        <td><%= town.section %></td>
        <td><%= town.kap_city %></td>
        <td><%= link_to 'Show', town %></td>
        <td><%= link_to 'Edit', edit_town_path(town) %></td>
        <td><%= link_to 'Destroy', town, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @towns %>
<br>

<%= link_to 'New Town', new_town_path %>

app/views/towns/new.html.erb
<h1>New Town</h1>

<%= render 'form', town: @town %>

<%= link_to 'Back', towns_path %>

app/views/towns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @town.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @town.title %>
</p>

<p>
  <strong>Kal townid:</strong>
  <%= @town.kal_townID %>
</p>

<p>
  <strong>Kap townid:</strong>
  <%= @town.kap_townID %>
</p>

<p>
  <strong>Kal type:</strong>
  <%= @town.kal_type %>
</p>

<p>
  <strong>Kal base:</strong>
  <%= @town.kal_base %>
</p>

<p>
  <strong>Population:</strong>
  <%= @town.population %>
</p>

<p>
  <strong>Kap type:</strong>
  <%= @town.kap_type %>
</p>

<p>
  <strong>Section:</strong>
  <%= @town.section %>
</p>

<p>
  <strong>Kap city:</strong>
  <%= @town.kap_city %>
</p>

<%= link_to 'Edit', edit_town_path(@town) %> |
<%= link_to 'Back', towns_path %>